In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [2]:
#Extract CSV INTO DATA FRAME
World_population ="Resources/World_Population.csv"

In [3]:
World_sucide ="Resources/World_SucideRate.csv"

In [4]:
population_df = pd.read_csv(World_population)
sucide_df = pd.read_csv(World_sucide)

In [5]:
population_df.head()

,Unnamed: 0,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,North America,320.27638,324.44694,328.62014,332.72487,336.72143,340.74811,344.89548,349.07829,353.29390,...,417.83236,422.05268,426.06238,430.26938,434.47232,438.82964,443.34730,447.67394,451.83698,456.59331
1,Bermuda,0.05473,0.05491,0.05517,0.05551,0.05585,0.05618,0.05651,0.05683,0.05717,...,0.06361,0.06418,0.06476,0.06534,0.06591,0.06644,0.06692,0.06739,0.06784,0.06827
2,Canada,24.59330,24.90000,25.20190,25.45630,25.70180,25.94160,26.20380,26.54970,26.89480,...,31.37674,31.64096,31.88931,32.13476,32.38638,32.65668,32.93596,33.21270,33.48721,33.75974
3,Greenland,0.05021,0.05103,0.05166,0.05211,0.05263,0.05315,0.05364,0.05410,0.05485,...,0.05713,0.05736,0.05754,0.05770,0.05778,0.05764,0.05753,0.05756,0.05760,0.05764
4,Mexico,68.34748,69.96926,71.64090,73.36288,75.08014,76.76723,78.44243,80.12249,81.78182,...,101.24696,102.47993,103.71806,104.95959,106.20290,107.44953,108.70089,109.95540,111.21179,112.46886

In [6]:
#Renaming un-named column to country 
population_df = population_df.rename(columns={'Unnamed: 0': 'country'})
#population_df['country_code'] = ['N/A'] * len(population_df['country'])
population_df

,country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,North America,320.27638,324.44694,328.62014,332.72487,336.72143,340.74811,344.89548,349.07829,353.29390,...,417.83236,422.05268,426.06238,430.26938,434.47232,438.82964,443.34730,447.67394,451.83698,456.59331
1,Bermuda,0.05473,0.05491,0.05517,0.05551,0.05585,0.05618,0.05651,0.05683,0.05717,...,0.06361,0.06418,0.06476,0.06534,0.06591,0.06644,0.06692,0.06739,0.06784,0.06827
2,Canada,24.59330,24.90000,25.20190,25.45630,25.70180,25.94160,26.20380,26.54970,26.89480,...,31.37674,31.64096,31.88931,32.13476,32.38638,32.65668,32.93596,33.21270,33.48721,33.75974
3,Greenland,0.05021,0.05103,0.05166,0.05211,0.05263,0.05315,0.05364,0.05410,0.05485,...,0.05713,0.05736,0.05754,0.05770,0.05778,0.05764,0.05753,0.05756,0.05760,0.05764
4,Mexico,68.34748,69.96926,71.64090,73.36288,75.08014,76.76723,78.44243,80.12249,81.78182,...,101.24696,102.47993,103.71806,104.95959,106.20290,107.44953,108.70089,109.95540,111.21179,112.46886
5,Saint Pierre and Miquelon,0.00599,0.00601,0.00605,0.00607,0.00611,0.00616,0.00621,0.00625,0.00628,...,0.00637,0.00633,0.00629,0.00625,0.00620,0.00615,0.00610,0.00605,0.00600,0.00594
6,United States,227.22468,229.46571,231.66446,233.79199,235.82490,237.92380,240.13289,242.28892,244.49898,...,285.08156,287.80391,290.32642,293.04574,295.75315,298.59321,301.57990,304.37485,307.00655,310.23286
7,Central & South America,293.05856,299.43033,305.95253,312.51136,318.87955,325.22704,331.82291,338.59859,345.44544,...,427.24012,433.05116,438.97976,445.01525,451.05504,457.01699,462.89157,468.73872,474.53897,480.01228
8,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Antigua and Barbuda,0.06855,0.06826,0.06801,0.06562,0.06447,0.06440,0.06440,0.06442,0.06443,...,0.07673,0.07794,0.07907,0.08019,0.08128,0.08234,0.08343,0.08452,0.08563,0.08675
10,Argentina,28.36980,28.84806,29.32988,29.79355,30.23064,30.67176,31.14499,31.62462,32.09932,...,37.69417,37.99945,38.33688,38.74183,39.18126,39.61443,40.04882,40.48200,40.91358,41.34320
11,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,0.05980,0.05918,0.05950,...,0.09097,0.09217,0.09372,0.09546,0.09698,0.09850,0.10002,0.10154,0.10307,0.10459
12,"Bahamas, The",0.20976,0.21345,0.21713,0.22086,0.22462,0.22820,0.23143,0.23448,0.23771,...,0.28569,0.28858,0.29135,0.29406,0.29671,0.29929,0.30197,0.30473,0.30755,0.31043
13,Barbados,0.25197,0.25236,0.25348,0.25485,0.25611,0.25725,0.25827,0.25912,0.25995,...,0.27491,0.27622,0.27755,0.27882,0.28004,0.28121,0.28236,0.28350,0.28459,0.28565
14,Belize,0.14442,0.14921,0.15330,0.15685,0.16081,0.16556,0.17124,0.17635,0.18140,...,0.25464,0.26130,0.26796,0.27462,0.28129,0.28795,0.29461,0.30127,0.30790,0.31452
15,Bolivia,5.44130,5.54522,5.64222,5.73743,5.83429,5.93494,6.04135,6.15637,6.28316,...,8.36745,8.54249,8.71906,8.89597,9.07294,9.24971,9.42594,9.60126,9.77525,9.94742
16,Brazil,123.01963,125.99213,129.02765,131.96012,134.69947,137.38198,140.19628,143.02654,145.87275,...,178.86966,181.41759,183.95992,186.48860,188.99308,191.46901,193.91858,196.34259,198.73927,201.10333
17,Cayman Islands,0.01708,0.01790,0.01852,0.01909,0.02002,0.02085,0.02144,0.02207,0.02450,...,0.03962,0.04080,0.04199,0.04316,0.04434,0.04552,0.04669,0.04786,0.04904,0.05021
18,Chile,11.09372,11.28230,11.48711,11.68662,11.87977,12.06780,12.26100,12.46452,12.67869,...,15.33189,15.50394,15.67191,15.83563,15.99504,16.15084,16.30385,16.45414,16.60171,16.74649
19,Colombia,26.63129,27.21489,27.82604,28.45499,29.09546,29.74762,30.41039,31.08530,31.77087,...,39.31245,39.80495,40.35102,40.92215,41.48778,42.04625,42.59732,43.14111,43.67737,44.20529
20,Costa Rica,2.29912,2.35729,2.42437,2.49435,2.56760,2.64431,2.72338,2.79934,2.87412,...,3.95621,4.02095,4.08382,4.14670,4.20869,4.26977,4.33113,4.39324,4.45505,4.51622
21,Cuba,9.65298,9.71198,9.78922,9.88126,9.97373,10.06563,10.14438,10.21682,10.30552,...,11.15582,11.20269,11.24668,11.28785,11.32615,11.36155,11.39404,11.42395,11.45165,11.47746
22,Dominica,0.07389,0.07352,0.07381,0.07429,0.07399,0.07311,0.07238,0.07182,0.07134,...,0.07121,0.07153,0.07173,0.07193,0.07212,0.07225,0.07238,0.07251,0.07266,0.07281
23,Dominican Republic,5.69686,5.83171,5.96874,6.10582,6.24155,6.37855,6.51682,6.65696,6.79877,...,8.61355,8.75690,8.89658,9.03239,9.16447,9.29504,9.42623,9.55818,9.69079,9.82382
24,Ecuador,7.92050,8.14108,8.36585,8.59349,8.82583,9.06166,9.30108,9.54516,9.79412,...,12.62912,12.82728,13.07418,13.36840,13.66232,13.91706,14.13496,14.35447,14.57310,14.79061
25,El Salvador,4.57041,4.51972,4.47992,4.52671,4.59375,4.67105,4.75832,4.85014,4.93899,...,5.88370,5.90183,5.91985,5.93512,5.95622,5.97089,5.98175,6.00645,6.03060,6.05206
26,Falkland Islands (Islas Malvinas),0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,...,0.00290,0.00293,0.00297,0.00297,0.00297,0.00297,0.00297,0.00314,0.00314,0.00314
27,French Guiana,0.07000,0.07000,0.07000,0.08000,0.08000,0.09000,0.09000,0.10000,0.11000,...,0.17756,0.18224,0.18692,0.19131,0.19131,0.19131,0.19131,0.19131,0.19131,0.19131
28,Grenada,0.09016,0.09235,0.09241,0.09253,0.09274,0.09306,0.09355,0.09406,0.09429,...,0.10229,0.10284,0.10332,0.10397,0.10459,0.10520,0.10589,0.10656,0.10720,0.10782
29,Guadeloupe,0.33700,0.33900,0.34100,0.34500,0.35000,0.35400,0.35800,0.36300,0.36700,...,0.43117,0.43568,0.44019,0.44452,0.44452,0.44452,0.44452,0.44452,0.44452,0.44452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Japan,116.80731,117.64809,118.45497,119.26995,120.03470,120.75434,121.49191,122.09133,122.61300,...,126.97191,127.18724,127.35774,127.48050,127.53719,127.51517,127.43349,127.28842,127.07868,126.80443
203,Kiribati,0.05754,0.05845,0.05935,0.06025,0.06115,0.06203,0.06377,0.06559,0.06748,...,0.08676,0.08826,0.08970,0.09112,0.09259,0.09406,0.09548,0.09686,0.09819,0.09948
204,"Korea, North",17.11363,17.38401,17.64752,17.91799,18.19600,18.48142,18.77246,19.06755,19.37114,...,21.49473,21.71214,21.89828,22.05448,22.19857,22.33156,22.45422,22.56535,22.66535,22.75728
205,"Korea, South",38.12400,38.72300,39.32600,39.91000,40.40600,40.80600,41.21400,41.62200,42.03100,...,47.17781,47.43728,47.65663,47.85385,48.00516,48.12356,48.25015,48.37939,48.50897,48.63607
206,Laos,3.29316,3.33698,3.41116,3.49496,3.57671,3.65717,3.76177,3.86931,3.97988,...,5.49852,5.57803,5.65400,5.74604,5.83636,5.93079,6.03541,6.14518,6.25687,6.36816
207,Macau,0.25577,0.26093,0.27081,0.28545,0.29898,0.30584,0.31220,0.32298,0.33214,...,0.43478,0.43898,0.44418,0.45523,0.47403,0.49943,0.52553,0.54567,0.55985,0.56796
208,Malaysia,13.46009,13.87521,14.30829,14.75262,15.19792,15.64911,16.11117,16.57890,17.05511,...,23.73736,24.28261,24.88040,25.47547,25.96812,26.43216,26.89556,27.35776,27.81787,28.27473
209,Maldives,0.15287,0.15725,0.16190,0.16685,0.17210,0.17730,0.18461,0.19221,0.20008,...,0.30591,0.31186,0.31849,0.32660,0.33625,0.34812,0.36497,0.38593,0.39633,0.39565
210,Mongolia,1.66238,1.70883,1.75603,1.80500,1.85569,1.90770,1.96080,2.01513,2.07072,...,2.70447,2.74455,2.78408,2.82457,2.86599,2.90840,2.95179,2.99608,3.04114,3.08692
211,Nauru,0.00771,0.00785,0.00800,0.00815,0.00833,0.00852,0.00871,0.00891,0.00910,...,0.00989,0.00992,0.00993,0.00997,0.01001,0.00957,0.00912,0.00916,0.00921,0.00927
212,Nepal,14.66525,15.01086,15.37507,15.75685,16.15506,16.56998,17.00221,17.45269,17.92208,...,25.33561,25.81505,26.27538,26.70832,27.09387,27.45895,27.82789,28.19696,28.56338,28.95185
213,New Caledonia,0.13940,0.14250,0.14500,0.14658,0.14966,0.15259,0.15558,0.15873,0.16194,...,0.21528,0.21944,0.22369,0.22802,0.23240,0.23651,0.24045,0.24445,0.24841,0.25235
214,New Zealand,3.16815,3.18345,3.21490,3.25645,3.29609,3.32181,3.33863,3.35049,3.35931,...,3.83576,3.89633,3.95813,4.00601,4.04606,4.08780,4.13018,4.17130,4.21126,4.25012
215,Niue,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,...,0.00212,0.00213,0.00215,0.00216,0.00216,0.00216,0.00216,0.00216,0.00216,0.00216
216,Pakistan,85.21912,90.97508,94.09612,96.88143,99.35434,102.07865,105.23962,108.58408,112.02109,...,156.79544,160.26923,163.16564,166.22361,169.27864,172.38187,175.49508,178.47939,181.45728,184.40479
217,Papua New Guinea,2.84640,2.91716,2.99100,3.06760,3.14690,3.22893,3.31375,3.40147,3.49213,...,4.93745,5.06260,5.18811,5.31389,5.43977,5.56556,5.69109,5.81623,5.94078,6.06452
218,Philippines,50.94018,52.22760,53.55718,54.88541,56.25788,57.70569,59.18595,60.64811,62.08071,...,83.09528,84.93641,86.75169,88.62179,90.43579,92.26694,94.15747,96.06168,97.97660,99.90018
219,Samoa,0.15904,0.16092,0.16074,0.16066,0.16066,0.16074,0.16086,0.16110,0.16152,...,0.17779,0.17943,0.18109,0.18277,0.18449,0.18625,0.18796,0.18950,0.19090,0.19200
220,Singapore,2.41390,2.53537,2.65187,2.68926,2.74330,2.74990,2.75007,2.79455,2.86927,...,4.12023,4.19778,4.27679,4.35389,4.42572,4.49215,4.55301,4.60817,4.65754,4.70107
221,Solomon Islands,0.23077,0.23874,0.24693,0.25535,0.26401,0.27293,0.28212,0.29154,0.30118,...,0.44591,0.45822,0.47065,0.48317,0.49575,0.50838,0.52107,0.53378,0.54649,0.55920
222,Sri Lanka,15.05597,15.31549,15.57547,15.78446,15.97692,16.18811,16.42379,16.66312,16.90308,...,19.64627,19.87007,20.09749,20.30327,20.50426,20.71793,20.92632,21.12877,21.32479,21.51399
223,Taiwan,17.84832,18.17743,18.50139,18.80339,19.08335,19.33736,19.55558,19.75780,19.97610,...,22.33581,22.45063,22.54347,22.62239,22.70108,22.78187,22.85887,22.92095,22.97435,23.02496
224,Thailand,47.02576,47.93650,48.82716,49.69425,50.53378,51.34181,52.12948,52.91034,53.68343,...,62.68514,63.21312,63.73055,64.24084,64.74260,65.23501,65.71702,66.18726,66.64481,67.08950
225,Timor-Leste (East Timor),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.99855,1.02005,1.04181,1.06384,1.08617,1.10878,1.13161,1.15463
226,Tonga,0.09136,0.09177,0.09220,0.09263,0.09288,0.09335,0.09374,0.09400,0.09332,...,0.10426,0.10616,0.10817,0.11026,0.11245,0.11471,0.11694,0.11901,0.12090,0.12258
227,U.S. Pacific Islands,0.13796,0.14283,0.14762,0.15281,0.15825,0.16406,0.17104,0.17903,0.18841,...,0.25365,0.25739,0.26116,0.26494,0.25814,0.24957,0.24888,0.24678,0.24424,0.24221
228,Vanuatu,0.11679,0.12026,0.12379,0.12738,0.13103,0.13473,0.13848,0.14227,0.14612,...,0.19317,0.19646,0.19971,0.20293,0.20609,0.20922,0.21234,0.21545,0.21852,0.22155
229,Vietnam,53.71520,54.90268,56.14218,57.43635,58.76204,60.09307,61.43983,62.82649,64.21135,...,80.20948,81.25796,82.29659,83.35245,84.42493,85.47054,86.51885,87.55836,88.57676,89.57113
230,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,World,4451.32679,4534.01064,4613.94102,4694.93620,4775.05313,4856.52116,4940.19470,5026.35348,5113.19070,...,6165.32364,6241.71768,6317.42640,6393.12094,6469.12974,6545.88444,6623.57196,6700.76588,6776.91747,6853.01941

In [7]:
# Taking first 3 character from the country column to new column country code colmun 
population_df['country_code'] = ['N/A'] * len(population_df['country'])

for i in range(len(population_df['country_code'])):
    code = population_df.loc[i, 'country']
    population_df.loc[i, 'country_code'] = code[:3]

In [8]:
population_df

,country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,country_code
0,North America,320.27638,324.44694,328.62014,332.72487,336.72143,340.74811,344.89548,349.07829,353.29390,...,422.05268,426.06238,430.26938,434.47232,438.82964,443.34730,447.67394,451.83698,456.59331,Nor
1,Bermuda,0.05473,0.05491,0.05517,0.05551,0.05585,0.05618,0.05651,0.05683,0.05717,...,0.06418,0.06476,0.06534,0.06591,0.06644,0.06692,0.06739,0.06784,0.06827,Ber
2,Canada,24.59330,24.90000,25.20190,25.45630,25.70180,25.94160,26.20380,26.54970,26.89480,...,31.64096,31.88931,32.13476,32.38638,32.65668,32.93596,33.21270,33.48721,33.75974,Can
3,Greenland,0.05021,0.05103,0.05166,0.05211,0.05263,0.05315,0.05364,0.05410,0.05485,...,0.05736,0.05754,0.05770,0.05778,0.05764,0.05753,0.05756,0.05760,0.05764,Gre
4,Mexico,68.34748,69.96926,71.64090,73.36288,75.08014,76.76723,78.44243,80.12249,81.78182,...,102.47993,103.71806,104.95959,106.20290,107.44953,108.70089,109.95540,111.21179,112.46886,Mex
5,Saint Pierre and Miquelon,0.00599,0.00601,0.00605,0.00607,0.00611,0.00616,0.00621,0.00625,0.00628,...,0.00633,0.00629,0.00625,0.00620,0.00615,0.00610,0.00605,0.00600,0.00594,Sai
6,United States,227.22468,229.46571,231.66446,233.79199,235.82490,237.92380,240.13289,242.28892,244.49898,...,287.80391,290.32642,293.04574,295.75315,298.59321,301.57990,304.37485,307.00655,310.23286,Uni
7,Central & South America,293.05856,299.43033,305.95253,312.51136,318.87955,325.22704,331.82291,338.59859,345.44544,...,433.05116,438.97976,445.01525,451.05504,457.01699,462.89157,468.73872,474.53897,480.01228,Cen
8,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ant
9,Antigua and Barbuda,0.06855,0.06826,0.06801,0.06562,0.06447,0.06440,0.06440,0.06442,0.06443,...,0.07794,0.07907,0.08019,0.08128,0.08234,0.08343,0.08452,0.08563,0.08675,Ant
10,Argentina,28.36980,28.84806,29.32988,29.79355,30.23064,30.67176,31.14499,31.62462,32.09932,...,37.99945,38.33688,38.74183,39.18126,39.61443,40.04882,40.48200,40.91358,41.34320,Arg
11,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,0.05980,0.05918,0.05950,...,0.09217,0.09372,0.09546,0.09698,0.09850,0.10002,0.10154,0.10307,0.10459,Aru
12,"Bahamas, The",0.20976,0.21345,0.21713,0.22086,0.22462,0.22820,0.23143,0.23448,0.23771,...,0.28858,0.29135,0.29406,0.29671,0.29929,0.30197,0.30473,0.30755,0.31043,Bah
13,Barbados,0.25197,0.25236,0.25348,0.25485,0.25611,0.25725,0.25827,0.25912,0.25995,...,0.27622,0.27755,0.27882,0.28004,0.28121,0.28236,0.28350,0.28459,0.28565,Bar
14,Belize,0.14442,0.14921,0.15330,0.15685,0.16081,0.16556,0.17124,0.17635,0.18140,...,0.26130,0.26796,0.27462,0.28129,0.28795,0.29461,0.30127,0.30790,0.31452,Bel
15,Bolivia,5.44130,5.54522,5.64222,5.73743,5.83429,5.93494,6.04135,6.15637,6.28316,...,8.54249,8.71906,8.89597,9.07294,9.24971,9.42594,9.60126,9.77525,9.94742,Bol
16,Brazil,123.01963,125.99213,129.02765,131.96012,134.69947,137.38198,140.19628,143.02654,145.87275,...,181.41759,183.95992,186.48860,188.99308,191.46901,193.91858,196.34259,198.73927,201.10333,Bra
17,Cayman Islands,0.01708,0.01790,0.01852,0.01909,0.02002,0.02085,0.02144,0.02207,0.02450,...,0.04080,0.04199,0.04316,0.04434,0.04552,0.04669,0.04786,0.04904,0.05021,Cay
18,Chile,11.09372,11.28230,11.48711,11.68662,11.87977,12.06780,12.26100,12.46452,12.67869,...,15.50394,15.67191,15.83563,15.99504,16.15084,16.30385,16.45414,16.60171,16.74649,Chi
19,Colombia,26.63129,27.21489,27.82604,28.45499,29.09546,29.74762,30.41039,31.08530,31.77087,...,39.80495,40.35102,40.92215,41.48778,42.04625,42.59732,43.14111,43.67737,44.20529,Col
20,Costa Rica,2.29912,2.35729,2.42437,2.49435,2.56760,2.64431,2.72338,2.79934,2.87412,...,4.02095,4.08382,4.14670,4.20869,4.26977,4.33113,4.39324,4.45505,4.51622,Cos
21,Cuba,9.65298,9.71198,9.78922,9.88126,9.97373,10.06563,10.14438,10.21682,10.30552,...,11.20269,11.24668,11.28785,11.32615,11.36155,11.39404,11.42395,11.45165,11.47746,Cub
22,Dominica,0.07389,0.07352,0.07381,0.07429,0.07399,0.07311,0.07238,0.07182,0.07134,...,0.07153,0.07173,0.07193,0.07212,0.07225,0.07238,0.07251,0.07266,0.07281,Dom
23,Dominican Republic,5.69686,5.83171,5.96874,6.10582,6.24155,6.37855,6.51682,6.65696,6.79877,...,8.75690,8.89658,9.03239,9.16447,9.29504,9.42623,9.55818,9.69079,9.82382,Dom
24,Ecuador,7.92050,8.14108,8.36585,8.59349,8.82583,9.06166,9.30108,9.54516,9.79412,...,12.82728,13.07418,13.36840,13.66232,13.91706,14.13496,14.35447,14.57310,14.79061,Ecu
25,El Salvador,4.57041,4.51972,4.47992,4.52671,4.59375,4.67105,4.75832,4.85014,4.93899,...,5.90183,5.91985,5.93512,5.95622,5.97089,5.98175,6.00645,6.03060,6.05206,El
26,Falkland Islands (Islas Malvinas),0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,...,0.00293,0.00297,0.00297,0.00297,0.00297,0.00297,0.00314,0.00314,0.00314,Fal
27,French Guiana,0.07000,0.07000,0.07000,0.08000,0.08000,0.09000,0.09000,0.10000,0.11000,...,0.18224,0.18692,0.19131,0.19131,0.19131,0.19131,0.19131,0.19131,0.19131,Fre
28,Grenada,0.09016,0.09235,0.09241,0.09253,0.09274,0.09306,0.09355,0.09406,0.09429,...,0.10284,0.10332,0.10397,0.10459,0.10520,0.10589,0.10656,0.10720,0.10782,Gre
29,Guadeloupe,0.33700,0.33900,0.34100,0.34500,0.35000,0.35400,0.35800,0.36300,0.36700,...,0.43568,0.44019,0.44452,0.44452,0.44452,0.44452,0.44452,0.44452,0.44452,Gua
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Japan,116.80731,117.64809,118.45497,119.26995,120.03470,120.75434,121.49191,122.09133,122.61300,...,127.18724,127.35774,127.48050,127.53719,127.51517,127.43349,127.28842,127.07868,126.80443,Jap
203,Kiribati,0.05754,0.05845,0.05935,0.06025,0.06115,0.06203,0.06377,0.06559,0.06748,...,0.08826,0.08970,0.09112,0.09259,0.09406,0.09548,0.09686,0.09819,0.09948,Kir
204,"Korea, North",17.11363,17.38401,17.64752,17.91799,18.19600,18.48142,18.77246,19.06755,19.37114,...,21.71214,21.89828,22.05448,22.19857,22.33156,22.45422,22.56535,22.66535,22.75728,Kor
205,"Korea, South",38.12400,38.72300,39.32600,39.91000,40.40600,40.80600,41.21400,41.62200,42.03100,...,47.43728,47.65663,47.85385,48.00516,48.12356,48.25015,48.37939,48.50897,48.63607,Kor
206,Laos,3.29316,3.33698,3.41116,3.49496,3.57671,3.65717,3.76177,3.86931,3.97988,...,5.57803,5.65400,5.74604,5.83636,5.93079,6.03541,6.14518,6.25687,6.36816,Lao
207,Macau,0.25577,0.26093,0.27081,0.28545,0.29898,0.30584,0.31220,0.32298,0.33214,...,0.43898,0.44418,0.45523,0.47403,0.49943,0.52553,0.54567,0.55985,0.56796,Mac
208,Malaysia,13.46009,13.87521,14.30829,14.75262,15.19792,15.64911,16.11117,16.57890,17.05511,...,24.28261,24.88040,25.47547,25.96812,26.43216,26.89556,27.35776,27.81787,28.27473,Mal
209,Maldives,0.15287,0.15725,0.16190,0.16685,0.17210,0.17730,0.18461,0.19221,0.20008,...,0.31186,0.31849,0.32660,0.33625,0.34812,0.36497,0.38593,0.39633,0.39565,Mal
210,Mongolia,1.66238,1.70883,1.75603,1.80500,1.85569,1.90770,1.96080,2.01513,2.07072,...,2.74455,2.78408,2.82457,2.86599,2.90840,2.95179,2.99608,3.04114,3.08692,Mon
211,Nauru,0.00771,0.00785,0.00800,0.00815,0.00833,0.00852,0.00871,0.00891,0.00910,...,0.00992,0.00993,0.00997,0.01001,0.00957,0.00912,0.00916,0.00921,0.00927,Nau
212,Nepal,14.66525,15.01086,15.37507,15.75685,16.15506,16.56998,17.00221,17.45269,17.92208,...,25.81505,26.27538,26.70832,27.09387,27.45895,27.82789,28.19696,28.56338,28.95185,Nep
213,New Caledonia,0.13940,0.14250,0.14500,0.14658,0.14966,0.15259,0.15558,0.15873,0.16194,...,0.21944,0.22369,0.22802,0.23240,0.23651,0.24045,0.24445,0.24841,0.25235,New
214,New Zealand,3.16815,3.18345,3.21490,3.25645,3.29609,3.32181,3.33863,3.35049,3.35931,...,3.89633,3.95813,4.00601,4.04606,4.08780,4.13018,4.17130,4.21126,4.25012,New
215,Niue,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,0.00200,...,0.00213,0.00215,0.00216,0.00216,0.00216,0.00216,0.00216,0.00216,0.00216,Niu
216,Pakistan,85.21912,90.97508,94.09612,96.88143,99.35434,102.07865,105.23962,108.58408,112.02109,...,160.26923,163.16564,166.22361,169.27864,172.38187,175.49508,178.47939,181.45728,184.40479,Pak
217,Papua New Guinea,2.84640,2.91716,2.99100,3.06760,3.14690,3.22893,3.31375,3.40147,3.49213,...,5.06260,5.18811,5.31389,5.43977,5.56556,5.69109,5.81623,5.94078,6.06452,Pap
218,Philippines,50.94018,52.22760,53.55718,54.88541,56.25788,57.70569,59.18595,60.64811,62.08071,...,84.93641,86.75169,88.62179,90.43579,92.26694,94.15747,96.06168,97.97660,99.90018,Phi
219,Samoa,0.15904,0.16092,0.16074,0.16066,0.16066,0.16074,0.16086,0.16110,0.16152,...,0.17943,0.18109,0.18277,0.18449,0.18625,0.18796,0.18950,0.19090,0.19200,Sam
220,Singapore,2.41390,2.53537,2.65187,2.68926,2.74330,2.74990,2.75007,2.79455,2.86927,...,4.19778,4.27679,4.35389,4.42572,4.49215,4.55301,4.60817,4.65754,4.70107,Sin
221,Solomon Islands,0.23077,0.23874,0.24693,0.25535,0.26401,0.27293,0.28212,0.29154,0.30118,...,0.45822,0.47065,0.48317,0.49575,0.50838,0.52107,0.53378,0.54649,0.55920,Sol
222,Sri Lanka,15.05597,15.31549,15.57547,15.78446,15.97692,16.18811,16.42379,16.66312,16.90308,...,19.87007,20.09749,20.30327,20.50426,20.71793,20.92632,21.12877,21.32479,21.51399,Sri
223,Taiwan,17.84832,18.17743,18.50139,18.80339,19.08335,19.33736,19.55558,19.75780,19.97610,...,22.45063,22.54347,22.62239,22.70108,22.78187,22.85887,22.92095,22.97435,23.02496,Tai
224,Thailand,47.02576,47.93650,48.82716,49.69425,50.53378,51.34181,52.12948,52.91034,53.68343,...,63.21312,63.73055,64.24084,64.74260,65.23501,65.71702,66.18726,66.64481,67.08950,Tha
225,Timor-Leste (East Timor),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.99855,1.02005,1.04181,1.06384,1.08617,1.10878,1.13161,1.15463,Tim
226,Tonga,0.09136,0.09177,0.09220,0.09263,0.09288,0.09335,0.09374,0.09400,0.09332,...,0.10616,0.10817,0.11026,0.11245,0.11471,0.11694,0.11901,0.12090,0.12258,Ton
227,U.S. Pacific Islands,0.13796,0.14283,0.14762,0.15281,0.15825,0.16406,0.17104,0.17903,0.18841,...,0.25739,0.26116,0.26494,0.25814,0.24957,0.24888,0.24678,0.24424,0.24221,U.S
228,Vanuatu,0.11679,0.12026,0.12379,0.12738,0.13103,0.13473,0.13848,0.14227,0.14612,...,0.19646,0.19971,0.20293,0.20609,0.20922,0.21234,0.21545,0.21852,0.22155,Van
229,Vietnam,53.71520,54.90268,56.14218,57.43635,58.76204,60.09307,61.43983,62.82649,64.21135,...,81.25796,82.29659,83.35245,84.42493,85.47054,86.51885,87.55836,88.57676,89.57113,Vie
230,Wake Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wak
231,World,4451.32679,4534.01064,4613.94102,4694.93620,4775.05313,4856.52116,4940.19470,5026.35348,5113.19070,...,6241.71768,6317.42640,6393.12094,6469.12974,6545.88444,6623.57196,6700.76588,6776.91747,6853.01941,Wor

In [9]:
cols = ['country','country_code','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010']
new_column = population_df[cols]
rename_col_dict = {
    "country": "countryName",
    "country_code": "country_code",
    "2000" : "year_2000",
    "2001" : "year_2001", 
    "2002" : "year_2002",
    "2003": "year_2003", 
    "2004" : "year_2004", 
    "2005": "year_2005", 
    "2006": "year_2006", 
    "2007": "year_2007", 
    "2008": "year_2008", 
    "2009": "year_2009", 
    "2010" : "year_2010"
}

new_column = new_column.rename(columns =rename_col_dict)
new_column = new_column.drop_duplicates("country_code")
new_column = new_column.dropna()
new_column = new_column.set_index("country_code")
new_column.head()

,countryName,year_2000,year_2001,year_2002,year_2003,year_2004,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010
country_code,,,,,,,,,,,,
Nor,North America,413.32450,417.83236,422.05268,426.06238,430.26938,434.47232,438.82964,443.34730,447.67394,451.83698,456.59331
Ber,Bermuda,0.06306,0.06361,0.06418,0.06476,0.06534,0.06591,0.06644,0.06692,0.06739,0.06784,0.06827
Can,Canada,31.09956,31.37674,31.64096,31.88931,32.13476,32.38638,32.65668,32.93596,33.21270,33.48721,33.75974
Gre,Greenland,0.05689,0.05713,0.05736,0.05754,0.05770,0.05778,0.05764,0.05753,0.05756,0.05760,0.05764
Mex,Mexico,99.92662,101.24696,102.47993,103.71806,104.95959,106.20290,107.44953,108.70089,109.95540,111.21179,112.46886

In [10]:
sucide_df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [11]:
sucide_df['country_code'] = ['N/A'] * len(sucide_df['country'])

for i in range(len(sucide_df['country'])):
    code = sucide_df.loc[i, 'country']
    sucide_df.loc[i, 'country_code'] = code[:3]

In [12]:
sucide_df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,country_code
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,Alb
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,Alb
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,Alb
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,Alb
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,Alb

In [13]:
sucide_df.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation',
       'country_code'],
      dtype='object')

In [14]:
#sucide_df = sucide_df.rename(columns={'gdp_for_year ($): 0': 'gdp_year ($)'})

In [15]:
sucid_col = ["country","country_code","year","sex","suicides_no", "gdp_per_capita ($)"]
sucid_col

['country', 'country_code', 'year', 'sex', 'suicides_no', 'gdp_per_capita ($)']

In [16]:
new_sucid_col = sucide_df[sucid_col]
new_sucid_col.head()

   country country_code  year     sex  suicides_no  gdp_per_capita ($)
0  Albania          Alb  1987    male           21                 796
1  Albania          Alb  1987    male           16                 796
2  Albania          Alb  1987  female           14                 796
3  Albania          Alb  1987    male            1                 796
4  Albania          Alb  1987    male            9                 796

In [17]:
rename2_col_dict = {
    "country": "countryName",
    "country_code": "country_code",
    "year" : "Year", 
    "sex" : "Sex",
    "suicides_no" : "SucidiesNumber",
    "gdp_per_capita ($)": "GDP_Per_capita"
    
}

new_sucid_col = new_sucid_col.rename(columns =rename2_col_dict)
new_sucid_col= new_sucid_col.set_index("country_code")
new_sucid_col.head()

             countryName  Year     Sex  SucidiesNumber  GDP_Per_capita
country_code
Alb              Albania  1987    male              21             796
Alb              Albania  1987    male              16             796
Alb              Albania  1987  female              14             796
Alb              Albania  1987    male               1             796
Alb              Albania  1987    male               9             796

In [22]:
conn_string = "mysql://root:santi2714@localhost:3306/world_population_db"
engine = create_engine(conn_string)

In [23]:
print(engine.table_names())

['population', 'sucide']

# Load DataFrames into database

In [24]:
read_column = pd.read_sql_table("population",engine)
read_column.head()

Empty DataFrame
Columns: [country_code, countryName, year_2000, year_2001, year_2002, year_2003, year_2004, year_2005, year_2006, year_2007, year_2008, year_2009, year_2010]
Index: []

In [25]:
new_column.to_sql(name='population', con=engine, if_exists='append', index=True)

In [ ]:
new_sucid_col.to_sql(name='sucide', con=engine, if_exists='append', index=True)